server:
  port: 8080
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scott?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 20
      max-active: 20
      min-idle: 5
      max-wait: 60000
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: root
      filter:
        stat:
          enabled: true
          merge-sql: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
        slf4j:
          enabled: true
mybatis:
  mapper-locations: classpath:/mapper/*.xml  # 当前xml文件放置的位置
  config-location: classpath:/mybatis-config.xml # 指明mybatis的配置文件是哪一个
logging:
  pattern:
    file: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
  file:
    name: /Users/sanyejiantai/Desktop/study/study_spb2/logs/springboot.log
  level:
    root: info
    com.evan: debug
